apiVersion: v1
kind: Service
metadata:
  name: tweet-db
  labels:
    name: tweet-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selectro:
    app: tweet-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tweet-db
spec:
  selectro:
    matchLabels:
      app: tweet-db
  serviceName: tweet-db
  replicas: 2
  template:
    metadata:
      labels:
        app: tweet-db
    spec:
      terminationGracePriodSecond: 10
      containers:
        - name: tweet-db
          image: mongo:5.0
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: tweet-db-pvc
              mountPath: /data/db
        -
