apiVersion: v1
kind: Service
metadata:
  name: reactapp
  labels:
    env: dev
spec:
  type: NodePort
  selector:
    app: twitter
    type: frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000