apiVersion: v1
kind: Service
metadata:
  name: goapp
  labels:
    app: twitter
    type: backend
spec:
  type: NodePort
  selector:
    app: twitter
    type: backend
  ports:
  - port: 4000
    targetPort: 4000
    # nodePort: 30001