version: '3.8'

services:

  backend:
    container_name: twtter-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      # - MONGO_URI=mongodb://admin:password@mongo:27017/test?authSource=admin
        - MONGO_URI=mongodb://mongo:27017
        - MONGO_USERNAME=root
        - MONGO_PASSWORD=password
        - SIGN_KEY="ILaNEKO9sVwMEhm/JEFnyU4OCc1LQ6AZOx97Oo4HKRA00IVHYMlk5wGJZ62uoKh2dZuF8yPXzsfF2sgBRLE9CUzGTU+UxSn7arPpTAcjS+hM4AtcMP20vY6Kf72vCWZtFzGtLDGn3733u/9mr34s7gqZq8g4zOyQp3IKXZgA0evx4/Lsg+yO2ullcaT7ww7LkL3Ktcg6FbC4Q29AdvNxWtYDmsgUofOWq6LlLeSHHaowgtmGCB+7RZMnzOdVVngQAvCPttrJo5c82nEdYQSOTZ4ua0r4FipDUl1M4t+HHnBYqWkm1EKBpl5QbyC7ft7eDoP4roXpGb5xJeOMdGrDOuIZ38XHJ23eaCjpY3tNDr82pkiU3Pk/FhCfygTNVP4SJp4hASPMsKgZ/ZDQGBYxZ/PjmRs4nOW8UIBcDza1VATV06TOgPiIKFVSd5SpWMrpNH3d3jdPklaCsos5lLT5v9ovSN+yNx/LMg4A+Pojwos17r4vc44BIWKq54FIKSNoPgc34LJcOiISNbpTwcfgnpHeFrUzbyf2qcsaOfWU1p/YGKQ2A2ESipm387PU6EVXJye+LYp7ngGedLk3XsXGYccb0w/LMVrfn3WYqQK3hUSx10a4RMtKiQ/RPOVGjcqpLm6UG30F3pWJaM5IJtclVHgXU3kaGL19zkL73cFolImz/b3iiLqnW3EOAsk0ErdWHPSONtkTV/8+SNqp56bWvF9K4tJQLATvMcmHuOr4LXOVgPPFEy3qE7+Si8u8Xtfhmhu72BOBDgF+pkNGWby4GTOOAJ0B8GjiXqkAA4f9oOO02k5tnwKPBTVLH3BrttYgtTC0u9fi1Xl7TNZ0gQGKmeeg1FzY4mqlkLUNWwxYs5mDLGX88vht/fRRt6/uxRfIxI1YrXb7ZNdg/WuP9JZ1DfK5DTnd33QMqsUc8UA2AkiJsk6gIzLuiDO+0y//DKHo2Y8qzy8ZmNaWIpQYaSmVpf7vbCaMdiJSP5wcDbnWnejQ2WX7GL8zYQQEkjqlM4paXJ6LZqiP4VA7V0ietjyWbQC6FDenQHupqNSlOAtQzYcvCR4D8310fMrSueXeByW/P6NHADV+m6Suu+iQIHGP6AFLM0azT+MkJWoHSTpWefm1bZS1dqljf0Bs+RD63p7lzlMPG9kimhCgbhfsxyO1F9QyUpibM3zO443N4N3jTL1ZwbuAy4mcC+eZnZSOQZMZghZ3Nwrq/8dXGvxHE879EOptkguI94+ezusegBidRAU0Jm/JFySJYXmBjPFNtjbFpX1tS2Nwpoad/HdeyLRlKfGuGj1mRDnzBRivq1DWKFP9/roNDC6LUlkmBkyFQM0w0kpJo7aQXpYuG7hW4NLmMw==="
        - LOG_LEVEL=info
        - LOG_OUTPUT=stdout
    depends_on:
      - mongo
    links:
      - "mongo"
    ports:
      - "8080:8080"

  mongo:
    container_name: mongo
    image: mongo:4.0
    # auth mode enable
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
