version: '3.8'

services:

  backend:
    container_name: twtter-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      # - MONGO_URI=mongodb://admin:password@mongo:27017/test?authSource=admin
        - MONGO_URI=mongodb://mongo:27017
        - MONGO_USERNAME=root
        - MONGO_PASSWORD=password
        - LOG_LEVEL=info
        - LOG_OUTPUT=/app/logs
    depends_on:
      - mongo
    links:
      - "mongo"
    ports:
      - "8080:8080"

  mongo:
    container_name: mongo
    image: mongo:4.0
    # auth mode enable
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
