apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: twitter
    type: web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: twitter
    type: web

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: twitter
    type: web
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        server_tokens   off;

        proxy_cache_path /var/cache/nginx keys_zone=STATIC:10m max_size=1g inactive=10d;
        proxy_temp_path  /var/cache/nginx/tmp;

        server {
            listen        80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            location / {
                proxy_pass http://react-svc:3000/;
            }

            # location /public/ {
            #     proxy_pass http://${APPLICATION_HOST}/public/;
            #     proxy_ignore_headers Cache-Control Expires;
            #     proxy_buffering on;
            #     proxy_cache STATIC;
            #     proxy_cache_valid any 10d;
            #     add_header X-Nginx-Cache $upstream_cache_status;
            # }
        }

        # include /etc/nginx/conf.d/*.conf;
        # ConfigMap
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: twitter
    type: web
spec:
  containers:
  - name: nginx
    image: nginx:latest
    # image: twitter-nginx:v1.0.0
    # imagePullPolicy: Never
    ports:
    - containerPort: 80
    env:
    - name: "APPLICATION_HOST"
      value: "react-svc:3000"
    volumeMounts:
    - name: config-volume
      # mountPath: /home/nginx
      mountPath: /etc/nginx/
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config