# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:5.0
    # restart: always
    # auth mod enable
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
