---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
  labels:
    app: twitter
    type: database
type: Opaque
data:
  root_password: UGFzc3cwcmQ=
  root_username: YWRtaW4=
  keyfile: a1RzZFZPdGFkZXpmRENETUxuYkt6UFRwcXF3ZndIcHJwMnBDSUFvNHNKWFJKUzBkbG1Jd2hSQ1Z4WE9jWVpubzZBb1lWdkQ5UFgwekdnVzFNVE5kV3VYQzUyeWFYbi8xSk1HZVYxNm56ZFljTHBsVHBRUlZhb3RyOHlJZkNRYk16b2RiekcvTU5RNWc1aUtPSWVGM1dvTTZKUlR2NnhPb1U5N09Sb2E5R2doaDdQOUlsTjlvZ0ppZ1czMXJRMno4MFBtNXMreVkvWnpxaTRHRFRUSkYwWkJMVTNqSiszdEFJa0pJY0UwSGFFbXBqUldTaGh0OXlyYUR1c25sK3E4UHFITVM0SGsvRDFqdzI0ejRsRnRyMS80Nk1MbEd5YllySitPZGFsckl5VWpULzZnN2JvOExQNWxsWTJ1ZlRPZlBIYVltWnlEUjRmcHpTWkFycGF2NG8va0x2VG9sK2ZDZTQrOFNxMmM0Slk2RHJFU20zekVyLzRFbFlEMXpEcEtXSHl1MXpZQ2R3MXk1R2Z5ZXI1MzlSaW51bnQ5TklxWW9saW1lQlVRU0NLSk5VQ1NzcGhHSk5SRHdFT3JOT1h1aUcyRjkxaEtDL0kxUEM1ZHh1THY5bXM5MXN3M0lVM0M0U0pwSHhRdHJtVjBYM1orTitjMjlVbm1JSHJzYU15U3lkMW5OY1c1a3g5MHhrRGF2TUp2NkNYTEVhbGNYanRwcmx5ZGs3OUt0UkxOd2Rhak9ObEZvMGNmTGRWWE1QWUlwZjM2YkxOTHdKQVJwK3cycXRmdmlsSmtmc29NRG9pcmVrU1hNYmxseFp6UHZFa2tqQmNGdWo0NWV6a0FVOGtiQWdnZ1liR05VTUZDZ2I1VXZwcUZ3ZkNoNFNybC82c2xuVjU3TSs4YVJmcWVEc2lzczFrTVN3K0FqenZrbUk4bnFhN1V3WEU2MDRvOXRUYUFkNkNYektPQVh3bEdkcHlNYVpSdWFpMVJ5QldsWVZaOXdMT3djNlNpbjBHOVZscEFzR2xuTGNOUEp1cmhlbERkSzI5Y1Z0eHBPNHFFdVlHYkpleS8rMU9pR0c1R1pzUTBxMkNhNDVoWVZEQVpqcWtLanM0YlZwcWZkbmoyUnlWbVY4cjM4UzhLdXV0cGtpUGY2UEdpZXhSRm5NR3hYYjJJazBYRHZLTU9BSFhxaG0yOGtlL2tacXVkb2RkcXBFdkxDc3Jvdm14Unc2MDBOdEtLUHhZaW9UMy9tTWI0ZS94MDVNaDFWeTJqeEU3bW0zWEdnSXkwMEtqWk90K2VvK1RUeGxHaFhUY2IyV2RVTXlEdDlKWGNKL044end2VTh0QmdEVThEckgvcXlyZkh4TjgzRwo=

---
apiVersion: v1
kind: Pod
metadata:
  name: goapp
  labels:
    app: twitter
    type: application
spec:
  containers:
  - name: go
    image: twitter-app:v1.0.0
    imagePullPolicy: Never
    ports:
    - containerPort: 4000
    env:
    - name: "MONGO_USERNAME"
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: "root_username"
    - name: "MONGO_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: "root_password"
    - name: "MONGO_HOSTS"
      value: "mongo-0.db-svc:27017,mongo-1.db-svc:27017,mongo-2.db-svc:27017"
    - name: "MONGO_URI"
      value: "mongodb://mongo-1.db-svc:27017"
    - name: "PORT"
      value: "4000"
    - name: "MONGO_DATABASE"
      value: "twitter"
    - name: "MONGO_REPLICASET"
      value: "rs0"