---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
  labels:
    app: twitter
    type: database
type: Opaque
data:
  root_password: UGFzc3cwcmQ=
  root_username: YWRtaW4=
  keyfile: a1RzZFZPdGFkZXpmRENETUxuYkt6UFRwcXF3ZndIcHJwMnBDSUFvNHNKWFJKUzBkbG1Jd2hSQ1Z4WE9jWVpubzZBb1lWdkQ5UFgwekdnVzFNVE5kV3VYQzUyeWFYbi8xSk1HZVYxNm56ZFljTHBsVHBRUlZhb3RyOHlJZkNRYk16b2RiekcvTU5RNWc1aUtPSWVGM1dvTTZKUlR2NnhPb1U5N09Sb2E5R2doaDdQOUlsTjlvZ0ppZ1czMXJRMno4MFBtNXMreVkvWnpxaTRHRFRUSkYwWkJMVTNqSiszdEFJa0pJY0UwSGFFbXBqUldTaGh0OXlyYUR1c25sK3E4UHFITVM0SGsvRDFqdzI0ejRsRnRyMS80Nk1MbEd5YllySitPZGFsckl5VWpULzZnN2JvOExQNWxsWTJ1ZlRPZlBIYVltWnlEUjRmcHpTWkFycGF2NG8va0x2VG9sK2ZDZTQrOFNxMmM0Slk2RHJFU20zekVyLzRFbFlEMXpEcEtXSHl1MXpZQ2R3MXk1R2Z5ZXI1MzlSaW51bnQ5TklxWW9saW1lQlVRU0NLSk5VQ1NzcGhHSk5SRHdFT3JOT1h1aUcyRjkxaEtDL0kxUEM1ZHh1THY5bXM5MXN3M0lVM0M0U0pwSHhRdHJtVjBYM1orTitjMjlVbm1JSHJzYU15U3lkMW5OY1c1a3g5MHhrRGF2TUp2NkNYTEVhbGNYanRwcmx5ZGs3OUt0UkxOd2Rhak9ObEZvMGNmTGRWWE1QWUlwZjM2YkxOTHdKQVJwK3cycXRmdmlsSmtmc29NRG9pcmVrU1hNYmxseFp6UHZFa2tqQmNGdWo0NWV6a0FVOGtiQWdnZ1liR05VTUZDZ2I1VXZwcUZ3ZkNoNFNybC82c2xuVjU3TSs4YVJmcWVEc2lzczFrTVN3K0FqenZrbUk4bnFhN1V3WEU2MDRvOXRUYUFkNkNYektPQVh3bEdkcHlNYVpSdWFpMVJ5QldsWVZaOXdMT3djNlNpbjBHOVZscEFzR2xuTGNOUEp1cmhlbERkSzI5Y1Z0eHBPNHFFdVlHYkpleS8rMU9pR0c1R1pzUTBxMkNhNDVoWVZEQVpqcWtLanM0YlZwcWZkbmoyUnlWbVY4cjM4UzhLdXV0cGtpUGY2UEdpZXhSRm5NR3hYYjJJazBYRHZLTU9BSFhxaG0yOGtlL2tacXVkb2RkcXBFdkxDc3Jvdm14Unc2MDBOdEtLUHhZaW9UMy9tTWI0ZS94MDVNaDFWeTJqeEU3bW0zWEdnSXkwMEtqWk90K2VvK1RUeGxHaFhUY2IyV2RVTXlEdDlKWGNKL044end2VTh0QmdEVThEckgvcXlyZkh4TjgzRwo=
  sign_key: ILaNEKO9sVwMEhm/JEFnyU4OCc1LQ6AZOx97Oo4HKRA00IVHYMlk5wGJZ62uoKh2dZuF8yPXzsfF2sgBRLE9CUzGTU+UxSn7arPpTAcjS+hM4AtcMP20vY6Kf72vCWZtFzGtLDGn3733u/9mr34s7gqZq8g4zOyQp3IKXZgA0evx4/Lsg+yO2ullcaT7ww7LkL3Ktcg6FbC4Q29AdvNxWtYDmsgUofOWq6LlLeSHHaowgtmGCB+7RZMnzOdVVngQAvCPttrJo5c82nEdYQSOTZ4ua0r4FipDUl1M4t+HHnBYqWkm1EKBpl5QbyC7ft7eDoP4roXpGb5xJeOMdGrDOuIZ38XHJ23eaCjpY3tNDr82pkiU3Pk/FhCfygTNVP4SJp4hASPMsKgZ/ZDQGBYxZ/PjmRs4nOW8UIBcDza1VATV06TOgPiIKFVSd5SpWMrpNH3d3jdPklaCsos5lLT5v9ovSN+yNx/LMg4A+Pojwos17r4vc44BIWKq54FIKSNoPgc34LJcOiISNbpTwcfgnpHeFrUzbyf2qcsaOfWU1p/YGKQ2A2ESipm387PU6EVXJye+LYp7ngGedLk3XsXGYccb0w/LMVrfn3WYqQK3hUSx10a4RMtKiQ/RPOVGjcqpLm6UG30F3pWJaM5IJtclVHgXU3kaGL19zkL73cFolImz/b3iiLqnW3EOAsk0ErdWHPSONtkTV/8+SNqp56bWvF9K4tJQLATvMcmHuOr4LXOVgPPFEy3qE7+Si8u8Xtfhmhu72BOBDgF+pkNGWby4GTOOAJ0B8GjiXqkAA4f9oOO02k5tnwKPBTVLH3BrttYgtTC0u9fi1Xl7TNZ0gQGKmeeg1FzY4mqlkLUNWwxYs5mDLGX88vht/fRRt6/uxRfIxI1YrXb7ZNdg/WuP9JZ1DfK5DTnd33QMqsUc8UA2AkiJsk6gIzLuiDO+0y//DKHo2Y8qzy8ZmNaWIpQYaSmVpf7vbCaMdiJSP5wcDbnWnejQ2WX7GL8zYQQEkjqlM4paXJ6LZqiP4VA7V0ietjyWbQC6FDenQHupqNSlOAtQzYcvCR4D8310fMrSueXeByW/P6NHADV+m6Suu+iQIHGP6AFLM0azT+MkJWoHSTpWefm1bZS1dqljf0Bs+RD63p7lzlMPG9kimhCgbhfsxyO1F9QyUpibM3zO443N4N3jTL1ZwbuAy4mcC+eZnZSOQZMZghZ3Nwrq/8dXGvxHE879EOptkguI94+ezusegBidRAU0Jm/JFySJYXmBjPFNtjbFpX1tS2Nwpoad/HdeyLRlKfGuGj1mRDnzBRivq1DWKFP9/roNDC6LUlkmBkyFQM0w0kpJo7aQXpYuG7hW4NLmMw===

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  labels:
    app: twitter
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twitter
      type: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 14
  template:
    metadata:
      name: goapp
      labels: 
        app: twitter
        type: backend
    spec:
      containers:
      - name: go
        image: 102665740320.dkr.ecr.ap-northeast-1.amazonaws.com/twtter-backend:v1.0.1
        ports:
        - containerPort: 4000
        env:
        - name: "MONGO_USERNAME"
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: "root_username"
        - name: "MONGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: "root_password"
        - name: "SIGN_KEY"
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: "sign_key"
        - name: "MONGO_URI"
          value: "mongodb://mongo-0.db-svc:27017,mongo-1.db-svc:27017,mongo-2.db-svc:27017,"
        - name: "PORT"
          value: "4000"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "LOG_OUTPUT"
          value: "stdout"
        - name: "MONGO_REPLICASET"
          value: "rs0"
        # - name: "MONGO_DATABASE"
        #   value: "twitter"
        # - name: "MONGO_HOSTS"
        #   value: "mongo-0.db-svc:27017,mongo-1.db-svc:27017,mongo-2.db-svc:27017,"

---
apiVersion: v1
kind: Service
metadata:
  name: golang-svc
  labels:
    app: twitter
    type: backend
spec:
  selector:
    app: twitter # deploymentの特定
    type: backend # deploymentの特定
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
